config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :clients
  root 'atendants#index'
  resources :atendants
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/atendant.rb
class Atendant < ApplicationRecord
end

app/models/client.rb
class Client < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/atendants_controller.rb
class AtendantsController < ApplicationController
  before_action :set_atendant, only: %i[ show edit update destroy ]

  # GET /atendants or /atendants.json
  def index
    @atendants = Atendant.all
  end

  # GET /atendants/1 or /atendants/1.json
  def show
  end

  # GET /atendants/new
  def new
    @atendant = Atendant.new
  end

  # GET /atendants/1/edit
  def edit
  end

  # POST /atendants or /atendants.json
  def create
    @atendant = Atendant.new(atendant_params)

    respond_to do |format|
      if @atendant.save
        format.html { redirect_to atendant_url(@atendant), notice: "Atendant was successfully created." }
        format.json { render :show, status: :created, location: @atendant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @atendant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atendants/1 or /atendants/1.json
  def update
    respond_to do |format|
      if @atendant.update(atendant_params)
        format.html { redirect_to atendant_url(@atendant), notice: "Atendant was successfully updated." }
        format.json { render :show, status: :ok, location: @atendant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @atendant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atendants/1 or /atendants/1.json
  def destroy
    @atendant.destroy

    respond_to do |format|
      format.html { redirect_to atendants_url, notice: "Atendant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atendant
      @atendant = Atendant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def atendant_params
      params.require(:atendant).permit(:name)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atendants_helper.rb
module AtendantsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/atendants/_atendant.html.slim
div id="#{dom_id atendant}"
  .card.my-5
    .card-header
      .card-title
        strong
          = atendant.name

    .card-body.d-flex.justify-content-between
      = link_to 'Show', atendant, class: 'btn btn-primary'
      = link_to 'Edit', edit_atendant_path(atendant), class: 'btn btn-warning'
      = button_to 'Destroy', atendant, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/atendants/_form.html.slim
/ <%= form_with(model: atendant) do |form| %>
/   <% if atendant.errors.any? %>
/     <div style="color: red">
/       <h2><%= pluralize(atendant.errors.count, "error") %> prohibited this atendant from being saved:</h2>

/       <ul>
/         <% atendant.errors.each do |error| %>
/           <li><%= error.full_message %></li>
/         <% end %>
/       </ul>
/     </div>
/   <% end %>

/   <div>
/     <%= form.label :name, style: "display: block" %>
/     <%= form.text_field :name %>
/   </div>

/   <div>
/     <%= form.submit %>
/   </div>
/ <% end %>

= form_with model: atendant do |form|
  .card.p-4.my-4
    .row
      .col-12
        .input-group.mb-3
          .input-group-text#addon1 @
          = form.text_field :name, class: 'form-control', placeholder: 'Name'
        input class='btn btn-primary' type='submit' name='commit' value='Create Atendant' data-disable-with='Create Atendant'

app/views/atendants/edit.html.erb
<h1>Editing atendant</h1>

<%= render "form", atendant: @atendant %>

<br>

<div>
  <%= link_to "Show this atendant", @atendant %> |
  <%= link_to "Back to atendants", atendants_path %>
</div>

app/views/atendants/index.html.slim
h2 Atendant

= link_to '+', new_atendant_path, class: 'btn btn-success'

.row.atendants
  - @atendants.each do |atendant|
    .col-4
      = render 'atendant', atendant:

app/views/atendants/new.html.slim
h2 New atendant

= render 'form', atendant: @atendant

= link_to 'Back to atendants', atendants_path

app/views/atendants/show.html.slim
= render 'atendant', atendant: @atendant

= link_to 'Back to atendants', atendants_path

app/views/clients/_client.html.slim
div id="#{dom_id client}"
  .card.my-5
    .card-header
      .card-title
        strong
          = client.name

    .card-body.d-flex.justify-content-between
      = link_to 'Show', client, class: 'btn btn-primary'
      = link_to 'Edit', edit_client_path(client), class: 'btn btn-warning'
      = button_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/clients/_form.html.slim
= form_with model: client do |form|
  .card.p-4.my-4
    - if client.errors.any?
      div style="color: red"
        h2
          = "#{pluralize(client.errors.count, 'error')} prohibited this client from being saved:"
        ul
          - client.errors.each do |error|
            li = error.full_message
    .row
      .col-12
        .input-group.mb-3
          .input-group-text#addon1 @
          = form.text_field :name, class: 'form-control', placeholder: 'Name'
        input class
          ='btn btn-primary' type='submit' name='commit' value='Create client' data-disable-with='Create client'

app/views/clients/edit.html.slim
h1 Editing client

== render "form", client: @client

br

div
  => link_to "Show this client", @client
  '|
  =< link_to "Back to clients", clients_path

app/views/clients/index.html.slim
h2 Clients

= link_to '+', new_client_path, class: 'btn btn-success'

.row.clients
  - @clients.each do |client|
    .col-4
      = render 'client', client:

app/views/clients/new.html.slim
h1 New client

== render "form", client: @client

br

div
  = link_to "Back to clients", clients_path

app/views/clients/show.html.slim
= render 'client', client: @client

= link_to 'Back to clients', clients_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
    title TicketSystem
    meta content="width=device-width,initial-scale=1" name="viewport"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag \
      'application',
      'data-turbo-track': 'reload',
      'type': 'module'

  body
    = render 'shared/navbar'
    .container-lg.mt-4
      p style="color: green" = notice

      = yield

app/views/shared/_navbar.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container-fluid
    a.navbar-brand[href="#"]
      | Navbar
    button.navbar-toggler[type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"]
      span.navbar-toggler-icon
    #navbarNav.collapse.navbar-collapse
      ul.navbar-nav
        li.nav-item.text-white
          = link_to 'Clients', clients_path, class: 'nav-link'
        li.nav-item.text-white
          = link_to 'Atendants', atendants_path, class: 'nav-link'